In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.preprocessing import FunctionTransformer

In [4]:
# question-1
salary=np.array([30000,50000,90000,811225])

log_transform=FunctionTransformer(np.log1p)

log_transformed=log_transform.transform(salary)

log_transformed

array([10.30898599, 10.81979828, 11.40757606, 13.60630196])

In [5]:
marks=np.array([4,9,16,25,36])
def squ(x):
    return x**2

squ_transform=FunctionTransformer(squ)
transformed=squ_transform.transform(marks)
transformed

array([  16,   81,  256,  625, 1296])

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [7]:
df = pd.DataFrame({
    'Price': [100, 200, 500, 1000],
    'Quantity': [1, 2, 3, 4]
})

pipe=Pipeline(steps=[
    ('log',FunctionTransformer(np.log1p)),
    ('scaler',StandardScaler())
]
)

price_transformed=pipe.fit_transform(df[['Price']])
print(price_transformed)

[[-1.31274668]
 [-0.52430958]
 [ 0.52203868]
 [ 1.31501758]]


In [8]:
x=np.array([[3,6,8],[5,6,7],[36,52,12]])

log_transform=FunctionTransformer(np.log1p)

x_transformed=log_transform.transform(x)
x_transformed

array([[1.38629436, 1.94591015, 2.19722458],
       [1.79175947, 1.94591015, 2.07944154],
       [3.61091791, 3.97029191, 2.56494936]])

In [11]:
x=np.array([[12,15],[25,21]])

def squ(x):
    return np.hstack((x,x**2))

squ_transform=FunctionTransformer(squ)

x_transformed=squ_transform.transform(x)
x_transformed

array([[ 12,  15, 144, 225],
       [ 25,  21, 625, 441]])

In [12]:
x=np.array([[12,24],[13,16]])

def squ(x):
    return np.vstack((x,x**2))

squ_transform=FunctionTransformer(squ)

x_transformed=squ_transform.transform(x)
x_transformed

array([[ 12,  24],
       [ 13,  16],
       [144, 576],
       [169, 256]])

In [14]:
x=np.array([[1,3],[34,np.nan]])

def cleanning(x):
    x[np.isnan(x)]=0
    return x

clean_transform=FunctionTransformer(cleanning)

x_transformed=clean_transform.transform(x)
x_transformed

array([[ 1.,  3.],
       [34.,  0.]])