# FUNCTION TRANSFORMERS---->
### The function transformers is a toll in sckit-learn a popular pyhton library in ml that allows you to apply a specified function to the input data. the function transformers can be usefull for performing custom transformation of imput data in ml pipeline.
##### function transformer takes as input a single function that will be applied to each sample in the data .the finction can not be any python function that takes a single argument,such as lambda function or a user defined function,the function should return the transformed sample.

In [3]:
from sklearn.preprocessing  import FunctionTransformer
import numpy as np

In [4]:
x=np.array([[1,2],[3,4]])

# define transformation fucntion

log_transform=FunctionTransformer(np.log1p)

# apply transformation to the data

x_transformed=log_transform.transform(x)

# view the transformed data

print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
# practical usecase

# 1. Custom Feature Engineering
x=np.array([[1,2],[3,4]])
# define the custom feature engineering function
def squ(x):
    return np.hstack((x,x**2))

square_transform=FunctionTransformer(squ)

x_transformed=square_transform.transform(x)

print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [8]:
x=np.array([[1,2],[3,4]])

def my_scalling(x):
    return x/np.max(x)

custom_transformer=FunctionTransformer(my_scalling)

x_transformed=custom_transformer.transform(x)

print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [11]:
x=np.array([[1,2],[3,np.nan]])

def my_cleaning(x):
    x[np.isnan(x)]=0
    return x

custom_transform=FunctionTransformer(my_cleaning)

x_transformer=custom_transform.transform(x)

print(x_transformer)

[[1. 2.]
 [3. 0.]]


In [12]:
import pandas as pd

In [13]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\placement - placement.csv")
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [15]:
x=df.drop(columns=['placed'])
y=df['placed']

In [16]:
log_transform=FunctionTransformer(np.log1p)

In [17]:
x_transformed=log_transform.transform(x)
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [23]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\insurance - insurance.csv")
df.head(3)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [28]:
df_1=df.select_dtypes(exclude=['object'])
df_1

age     bmi  children      charges
0      19  27.900         0  16884.92400
1      18  33.770         1   1725.55230
2      28  33.000         3   4449.46200
3      33  22.705         0  21984.47061
4      32  28.880         0   3866.85520
...   ...     ...       ...          ...
1333   50  30.970         3  10600.54830
1334   18  31.920         0   2205.98080
1335   18  36.850         0   1629.83350
1336   21  25.800         0   2007.94500
1337   61  29.070         0  29141.36030

[1338 rows x 4 columns]

In [29]:
df=df.drop(columns=['age','bmi','children','charges'])

In [30]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
oe=OrdinalEncoder(categories=[['female','male'],['yes','no'],['southwest', 'southeast', 'northwest', 'northeast']])

In [35]:
transformed=oe.fit_transform(df)

In [36]:
df_transformed=pd.DataFrame(transformed,columns=df.columns)

In [37]:
df_transformed

sex  smoker  region
0     0.0     0.0     0.0
1     1.0     1.0     1.0
2     1.0     1.0     1.0
3     1.0     1.0     2.0
4     1.0     1.0     2.0
...   ...     ...     ...
1333  1.0     1.0     2.0
1334  0.0     1.0     3.0
1335  0.0     1.0     1.0
1336  0.0     1.0     0.0
1337  0.0     0.0     2.0

[1338 rows x 3 columns]

In [39]:
df_new=pd.concat((df_1,df_transformed),axis=1)

In [40]:
log_transform=FunctionTransformer(np.log1p)

In [41]:
log_transform.transform(df_new)

age       bmi  children    charges       sex    smoker    region
0     2.995732  3.363842  0.000000   9.734236  0.000000  0.000000  0.000000
1     2.944439  3.548755  0.693147   7.453882  0.693147  0.693147  0.693147
2     3.367296  3.526361  1.386294   8.400763  0.693147  0.693147  0.693147
3     3.526361  3.165686  0.000000   9.998137  0.693147  0.693147  1.098612
4     3.496508  3.397189  0.000000   8.260455  0.693147  0.693147  1.098612
...        ...       ...       ...        ...       ...       ...       ...
1333  3.931826  3.464798  1.386294   9.268755  0.693147  0.693147  1.098612
1334  2.944439  3.494080  0.000000   7.699381  0.000000  0.693147  1.386294
1335  2.944439  3.633631  0.000000   7.396847  0.000000  0.693147  0.693147
1336  3.091042  3.288402  0.000000   7.605365  0.000000  0.693147  0.000000
1337  4.127134  3.403528  0.000000  10.279948  0.000000  0.000000  1.098612

[1338 rows x 7 columns]